namespace CrimsonCompass.Core
{
    public enum GameEventType
    {
        SESSION_OPEN,
        SESSION_CLOSE,
        LEAD_VIEWED,
        LEAD_RESOLVED,
        TRAVEL_STARTED,
        TRAVEL_COMPLETED,
        HYPOTHESIS_SUBMITTED,
        DISPROOF_RETURNED,
        CASE_RESOLVED,
        SAFE_HOUSE_RESET,
        HINT_OFFERED,
        HINT_USED,
        ACCUSATION_ATTEMPT,
        ACCUSATION_RESULT,
        HEAT_CHANGED,
        TIME_CHANGED,
        EPISODE_COMPLETED,
        MISSION_COMPLETED,
        WEEKLY_DROP_AVAILABLE,
        SCENE_LOADED,
        STATE_CHANGED,
        AGENT_MESSAGE,
        GAME_LOADED,
        NEW_GAME_STARTED,
        TEST_EVENT
    }
}
